name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rust-check-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src-tauri
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
      - name: Cargo check
        run: cargo check --all-targets
      - name: Cargo test
        run: cargo test --all-targets
      - name: Tauri build
        run: cargo tauri build --debug

